// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrzgAYDmLIp-dhzT7SZr7Y5P0RyEDaOfA',
    appId: '1:998686618225:web:474eff48d72159a9a721d0',
    messagingSenderId: '998686618225',
    projectId: 'app-movil-7871d',
    authDomain: 'app-movil-7871d.firebaseapp.com',
    storageBucket: 'app-movil-7871d.appspot.com',
    measurementId: 'G-CRHYXKPLLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGq0VyPLC-Jciq_9AY2IQOc_zZ-af-UE',
    appId: '1:998686618225:android:42b7d2f5b79530b1a721d0',
    messagingSenderId: '998686618225',
    projectId: 'app-movil-7871d',
    storageBucket: 'app-movil-7871d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTubeOlGG0aNwBGROXz_QCjxvxC6Ue8QM',
    appId: '1:998686618225:ios:abd233b171e95997a721d0',
    messagingSenderId: '998686618225',
    projectId: 'app-movil-7871d',
    storageBucket: 'app-movil-7871d.appspot.com',
    iosBundleId: 'com.example.proyectoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTubeOlGG0aNwBGROXz_QCjxvxC6Ue8QM',
    appId: '1:998686618225:ios:4e8e9a906070c67ba721d0',
    messagingSenderId: '998686618225',
    projectId: 'app-movil-7871d',
    storageBucket: 'app-movil-7871d.appspot.com',
    iosBundleId: 'com.example.proyectoapp.RunnerTests',
  );
}
